"""add product table

Revision ID: e48c11896a39
Revises: 
Create Date: 2024-02-22 15:57:17.917783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e48c11896a39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('apples', 'oranges', 'strawberries', 'bananas', 'pumpkins', 'cauliflowers', 'parsely', 'pepper', 'potatoes', 'carrots', 'tomatoes', name='productcategoryenum'), nullable=True),
    sa.Column('type', sa.Enum('vegetables', 'fruits', 'bread', 'meat', name='producttypeenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
